polkit-0.109 (WIP)

diff --git a/polkit/polkit-0.109-1bl1.src.patch b/polkit/polkit-0.109-1bl1.src.patch
--- a/polkit/polkit-0.109-1bl1.src.patch
+++ b/polkit/polkit-0.109-1bl1.src.patch
@@ -1,35 +1,26 @@
---- origsrc/polkit-0.105/configure.ac	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/configure.ac	2012-05-20 18:29:57.479934000 +0900
-@@ -195,11 +195,10 @@ if ! test -z "$with_authfw" ; then
+--- origsrc/polkit-0.109/configure.ac	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/configure.ac	2012-12-31 15:36:20.086679700 +0900
+@@ -226,7 +226,7 @@ if ! test -z "$with_authfw" ; then
    fi
    POLKIT_AUTHFW=$with_authfw
  else
 -  if test x$with_authdb = xdummy ; then
--    POLKIT_AUTHFW=none
--  else
--    POLKIT_AUTHFW=pam
--  fi
-+  case "$host_os" in
-+    cygwin*) POLKIT_AUTHFW=none ;;
-+    *)       POLKIT_AUTHFW=pam  ;;
-+  esac
- fi
- 
- AC_SUBST(POLKIT_AUTHFW)
---- origsrc/polkit-0.105/src/polkit/Makefile.am	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/src/polkit/Makefile.am	2012-05-20 18:29:57.479934000 +0900
-@@ -59,9 +59,8 @@ libpolkit_gobject_1include_HEADERS =
++  if test x$host_os = xcygwin ; then
+     POLKIT_AUTHFW=none
+   else
+     POLKIT_AUTHFW=pam
+--- origsrc/polkit-0.109/src/polkit/Makefile.am	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/src/polkit/Makefile.am	2012-12-31 15:37:44.144145800 +0900
+@@ -59,8 +59,7 @@ libpolkit_gobject_1include_HEADERS =
  	polkitpermission.h								\
          $(NULL)
  
 -libpolkit_gobject_1_la_SOURCES =                                   			\
 -	$(BUILT_SOURCES)								\
--        polkit.h									\
-+libpolkit_gobject_1_la_origsrc =							\
-+	polkit.h									\
++libpolkit_gobject_1_la_origsrc =                                   			\
+         polkit.h									\
  	polkitactiondescription.c		polkitactiondescription.h		\
  	polkitauthorityfeatures.h		polkitauthorityfeatures.c		\
- 	polkitdetails.c				polkitdetails.h				\
 @@ -81,6 +80,11 @@ libpolkit_gobject_1_la_SOURCES =
  	polkitpermission.c			polkitpermission.h			\
          $(NULL)
@@ -39,11 +30,11 @@
 +	$(libpolkit_gobject_1_la_origsrc)						\
 +	$(NULL)
 +
- if HAVE_SYSTEMD
+ if HAVE_LIBSYSTEMD_LOGIN
  libpolkit_gobject_1_la_SOURCES += \
  	polkitunixsession-systemd.c		polkitunixsession.h
 @@ -100,7 +104,7 @@ libpolkit_gobject_1_la_LIBADD =
- 	$(SYSTEMD_LIBS)							\
+ 	$(LIBSYSTEMD_LOGIN_LIBS)					\
          $(NULL)
  
 -libpolkit_gobject_1_la_LDFLAGS = -export-symbols-regex '(^polkit_.*)'
@@ -51,7 +42,7 @@
  
  if HAVE_INTROSPECTION
  
-@@ -119,7 +123,7 @@ Polkit_1_0_gir_CFLAGS = \
+@@ -121,7 +125,7 @@ Polkit_1_0_gir_CFLAGS = \
  	-D_POLKIT_COMPILATION			\
  	-I.. -I$(top_srcdir)/src
  Polkit_1_0_gir_LIBS = libpolkit-gobject-1.la
@@ -60,20 +51,20 @@
  Polkit_1_0_gir_EXPORT_PACKAGES = polkit-gobject-1
  
  include $(INTROSPECTION_MAKEFILE)
---- origsrc/polkit-0.105/src/polkitagent/Makefile.am	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/src/polkitagent/Makefile.am	2012-05-20 18:29:57.479934000 +0900
-@@ -53,9 +53,7 @@ libpolkit_agent_1include_HEADERS =
+--- origsrc/polkit-0.109/src/polkitagent/Makefile.am	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/src/polkitagent/Makefile.am	2012-12-31 15:39:24.864849000 +0900
+@@ -54,9 +54,7 @@ libpolkit_agent_1include_HEADERS =
  	polkitagenttextlistener.h							\
          $(NULL)
  
 -libpolkit_agent_1_la_SOURCES =                                   			\
 -	$(BUILT_SOURCES)								\
 -	$(marshal_built_sources)							\
-+libpolkit_agent_1_la_origsrc =								\
++libpolkit_agent_1_la_origsrc =                                   			\
          polkitagent.h									\
  	polkitagenttypes.h								\
  	polkitagentsession.h			polkitagentsession.c			\
-@@ -63,6 +61,12 @@ libpolkit_agent_1_la_SOURCES =
+@@ -64,6 +62,12 @@ libpolkit_agent_1_la_SOURCES =
  	polkitagenttextlistener.h		polkitagenttextlistener.c		\
          $(NULL)
  
@@ -86,16 +77,16 @@
  libpolkit_agent_1_la_CFLAGS =                                        	\
          -D_POLKIT_COMPILATION                                  		\
  	-D_POLKIT_AGENT_COMPILATION					\
-@@ -75,7 +79,7 @@ libpolkit_agent_1_la_LIBADD =
+@@ -76,7 +80,7 @@ libpolkit_agent_1_la_LIBADD =
  	$(EXPAT_LIBS)							\
          $(NULL)
  
 -libpolkit_agent_1_la_LDFLAGS = -export-symbols-regex '(^polkit_.*)'
 +libpolkit_agent_1_la_LDFLAGS = -export-symbols-regex '(^polkit_.*)' -no-undefined
  
- libexec_PROGRAMS = polkit-agent-helper-1
- 
-@@ -89,6 +93,9 @@ endif
+ libprivdir = $(prefix)/lib/polkit-1
+ libpriv_PROGRAMS = polkit-agent-helper-1
+@@ -91,6 +95,9 @@ endif
  if POLKIT_AUTHFW_SHADOW
  polkit_agent_helper_1_SOURCES += polkitagenthelper-shadow.c
  endif
@@ -105,7 +96,7 @@
  
  polkit_agent_helper_1_CFLAGS  = 					\
          -D_POLKIT_COMPILATION                                  		\
-@@ -121,7 +128,7 @@ PolkitAgent_1_0_gir_CFLAGS = \
+@@ -125,7 +132,7 @@ PolkitAgent_1_0_gir_CFLAGS = \
          -D_POLKIT_AGENT_COMPILATION		\
          -I.. -I$(top_srcdir)/src
  PolkitAgent_1_0_gir_LIBS = libpolkit-agent-1.la
@@ -114,8 +105,8 @@
  PolkitAgent_1_0_gir_EXPORT_PACKAGES = polkit-agent-1
  
  include $(INTROSPECTION_MAKEFILE)
---- origsrc/polkit-0.105/src/polkitagent/polkitagenthelper-none.c	1970-01-01 09:00:00.000000000 +0900
-+++ src/polkit-0.105/src/polkitagent/polkitagenthelper-none.c	2012-05-20 18:29:57.495559000 +0900
+--- origsrc/polkit-0.109/src/polkitagent/polkitagenthelper-none.c	1970-01-01 09:00:00.000000000 +0900
++++ src/polkit-0.109/src/polkitagent/polkitagenthelper-none.c	2012-12-31 15:40:16.437598200 +0900
 @@ -0,0 +1,11 @@
 +#include "config.h"
 +#include "polkitagenthelperprivate.h"
@@ -128,28 +119,17 @@
 +  flush_and_wait();
 +  return 0;
 +}
---- origsrc/polkit-0.105/src/polkitbackend/Makefile.am	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/src/polkitbackend/Makefile.am	2012-05-20 18:29:57.495559000 +0900
-@@ -65,7 +65,7 @@ libpolkit_backend_1_la_LIBADD =
- 	$(EXPAT_LIBS)							\
-         $(NULL)
- 
--libpolkit_backend_1_la_LDFLAGS = -export-symbols-regex '(^polkit_.*)'
-+libpolkit_backend_1_la_LDFLAGS = -export-symbols-regex '(^polkit_.*)' -no-undefined
- 
- CLEANFILES = $(BUILT_SOURCES)
- 
---- origsrc/polkit-0.105/src/polkitbackend/polkitbackendlocalauthority.c	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/src/polkitbackend/polkitbackendlocalauthority.c	2012-05-20 21:15:42.635881800 +0900
-@@ -698,6 +698,7 @@ get_users_in_net_group (PolkitIdentity
-   GList *ret;
- 
+--- origsrc/polkit-0.109/src/polkitbackend/polkitbackendinteractiveauthority.c	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/src/polkitbackend/polkitbackendinteractiveauthority.c	2012-12-31 15:52:57.403483000 +0900
+@@ -2113,6 +2113,7 @@ get_users_in_net_group (PolkitIdentity
    ret = NULL;
-+#if !defined(__CYGWIN__)
    name = polkit_unix_netgroup_get_name (POLKIT_UNIX_NETGROUP (group));
  
++#if !defined(__CYGWIN__)
    if (setnetgrent (name) == 0)
-@@ -739,6 +740,7 @@ get_users_in_net_group (PolkitIdentity
+     {
+       g_warning ("Error looking up net group with name %s: %s", name, g_strerror (errno));
+@@ -2152,6 +2153,7 @@ get_users_in_net_group (PolkitIdentity
  
   out:
    endnetgrent ();
@@ -157,29 +137,34 @@
    return ret;
  }
  
---- origsrc/polkit-0.105/src/polkitbackend/polkitbackendlocalauthorizationstore.c	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/src/polkitbackend/polkitbackendlocalauthorizationstore.c	2012-05-20 18:29:57.511184000 +0900
-@@ -735,8 +735,10 @@ polkit_backend_local_authorization_store
+--- origsrc/polkit-0.109/src/polkitbackend/polkitbackendjsauthority.c	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/src/polkitbackend/polkitbackendjsauthority.c	2012-12-31 15:51:47.637858000 +0900
+@@ -1568,6 +1568,7 @@ js_polkit_user_is_in_netgroup (JSContext
+   user = dJS_EncodeString (cx, user_str);
+   netgroup = dJS_EncodeString (cx, netgroup_str);
  
-           for (ll = authorization->netgroup_identities; ll != NULL; ll = ll->next)
-             {
 +#if !defined(__CYGWIN__)
-               if (innetgr ((const gchar *) ll->data, NULL, user_name, NULL))
-                 break;
+   if (innetgr (netgroup,
+                NULL,  /* host */
+                user,
+@@ -1575,6 +1576,7 @@ js_polkit_user_is_in_netgroup (JSContext
+     {
+       is_in_netgroup =  JS_TRUE;
+     }
 +#endif
-             }
-         }
  
---- origsrc/polkit-0.105/test/mocklibc/bin/mocklibc.in	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/test/mocklibc/bin/mocklibc.in	2012-05-20 18:29:57.511184000 +0900
+   dJS_free (cx, netgroup);
+   dJS_free (cx, user);
+--- origsrc/polkit-0.109/test/mocklibc/bin/mocklibc.in	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/test/mocklibc/bin/mocklibc.in	2012-12-31 15:58:11.721842400 +0900
 @@ -31,4 +31,4 @@ else
  fi
  
  # Exec the requested app, replacing this one
 -LD_PRELOAD="@libname@" exec $@
 +LD_PRELOAD="${LIBDIR}/@libname@" exec $@
---- origsrc/polkit-0.105/test/mocklibc/configure.ac	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/test/mocklibc/configure.ac	2012-05-20 18:29:57.511184000 +0900
+--- origsrc/polkit-0.109/test/mocklibc/configure.ac	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/test/mocklibc/configure.ac	2012-12-31 15:55:59.783365800 +0900
 @@ -26,7 +26,10 @@ AC_FUNC_MALLOC
  AC_CHECK_FUNCS([endgrent endpwent memset regcomp strdup])
  
@@ -192,9 +177,9 @@
  #AC_CONFIG_FILES([bin/mocklibc], [chmod +x bin/mocklibc], [libname=${libname}])
  #AC_CONFIG_FILES([bin/mocklibc-test], [chmod +x bin/mocklibc-test],
  #                [libname=${libname}]))
---- origsrc/polkit-0.105/test/mocklibc/src/Makefile.am	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/test/mocklibc/src/Makefile.am	2012-05-20 18:29:57.526809000 +0900
-@@ -1,8 +1,8 @@
+--- origsrc/polkit-0.109/test/mocklibc/src/Makefile.am	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/test/mocklibc/src/Makefile.am	2012-12-31 15:55:33.032389300 +0900
+@@ -1,6 +1,7 @@
  
  lib_LTLIBRARIES = libmocklibc.la
  libmocklibc_la_SOURCES = pwd.c grp.c netdb.c netgroup.c netgroup.h
@@ -202,10 +187,8 @@
  
  bin_PROGRAMS = mocklibc-debug-netgroup
  mocklibc_debug_netgroup_SOURCES = netgroup-debug.c netgroup-debug.h
- mocklibc_debug_netgroup_LDADD = libmocklibc.la
--
---- origsrc/polkit-0.105/test/mocklibc/src/grp.c	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/test/mocklibc/src/grp.c	2012-05-20 18:29:57.542434000 +0900
+--- origsrc/polkit-0.109/test/mocklibc/src/grp.c	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/test/mocklibc/src/grp.c	2012-12-31 16:05:39.997233000 +0900
 @@ -18,6 +18,10 @@
  
  #include <grp.h>
@@ -217,8 +200,8 @@
  #include <stdio.h>
  #include <stdlib.h>
  #include <string.h>
---- origsrc/polkit-0.105/test/mocklibc/src/pwd.c	2012-04-25 01:46:24.000000000 +0900
-+++ src/polkit-0.105/test/mocklibc/src/pwd.c	2012-05-20 18:29:57.542434000 +0900
+--- origsrc/polkit-0.109/test/mocklibc/src/pwd.c	2012-12-20 00:05:36.000000000 +0900
++++ src/polkit-0.109/test/mocklibc/src/pwd.c	2012-12-31 16:07:07.700358000 +0900
 @@ -18,6 +18,10 @@
  
  #include <pwd.h>
